### ISSUE TITLE
Update Java dependency

### ISSUE THREAD

**Issue by jvandijk** [Enrise/elasticsearch-formula#17]
@Enrise/matchminds what do you think about moving/copying your implementation of installing Oracle 8 Java and the JRE extension into this formula?

Elastic advices (https://www.elastic.co/guide/en/elasticsearch/reference/current/_installation.html) to use this, so why not make it default.

**Comment by jvandijk** [comment]
@syphernl do you see any issues if we do this?

**Comment by syphernl** [comment]
@jvandijk If its the recommendation of Elastic I guess it'll be best we follow it. Matchminds and our team already does that and that approach seems to work just fine.

**Comment by bsander** [comment]
I recall discussing this with Frank a few weeks ago already. Our main reason for doing it like this was so that we could do a controlled upgrade of our environments, but we're on 8 everywhere now so I'm fine with making it the default 👍

**Comment by jvandijk** [comment]
@bsander @syphernl the current elasticsearch state installs the JRE package. You still have to add the elasticsearch.java state too. I'd suggest to make this implicit by requiring the java state within the formula itself instead of when consuming the formula. So far I see less then 10 required code changes in the whole Saltmaster repo after this addition, which even is compatible without changes.

**Comment by eXistenZNL** [comment]
This repository has not been maintained for years, closing this issue.
